from LLM_patch_generation.args_parser import parse_arguments_validator
from LLM_patch_generation.patch_generator import ask_LLM

def main():
    validator_prompt = ""

    args = parse_arguments_validator()
    patches_filepath = args.Patches_directory_filepath

    MODELS = ['gemini-2.5-pro', 'gemini-2.5-flash', 'deepseek-V3.1', 'deepseek-R1']
    patches = {}

    # Appending correction patches to prompt
    for model in MODELS:
        with open(f'{patches_filepath}/{model}_patch.sh', 'r') as f:
            content = f.read()
            patches[model] = content
    
    validator_prompt +=  f'''==================================================\n'''
    for model, patch in patches.items():
        validator_prompt +=  f'''CORRECTION PATCH GENERATED BY {model}:\n'''
        validator_prompt +=  f'''{patch}\n'''
        validator_prompt +=  f'''==================================================\n'''

    print(validator_prompt)
    
    #response = ask_LLM('gpt-5.1', 'hello! how are you today?')

if __name__ == '__main__':
    main()